server:
  port: 9000
spring:
  kafka:
    consumer:
      bootstrap-servers: 10.0.0.238:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spark:
  app:
    name: Spring-test
  master: local[2]